### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by wh1sperC** [megvii-research/MOTRv2#18]
The following is my problem:
(motrv2) dcy@ubuntu:~/MOTRv2$ bash tools/train.sh configs/motrv2.args
+ PY_ARGS=
+ set -o pipefail
++ echo configs/motrv2.args
++ sed -e s/configs/exps/g
++ sed -e 's/.args$//g'
+ OUTPUT_BASE=exps/motrv2
+ mkdir -p exps/motrv2
++ seq 100
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run1
run1
+ continue
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run2
run2
+ continue
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run3
run3
+ continue
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run4
+ OUTPUT_DIR=exps/motrv2/run4
+ mkdir exps/motrv2/run4
+ break
+ echo 'Backing up to log dir: exps/motrv2/run4'
Backing up to log dir: exps/motrv2/run4
+ rmpyc
++ find -name __pycache__
+ rm -rf
++ find -name '*.pyc'
+ rm -rf
+ cp -r models datasets util main.py engine.py eval_detr.py seqmap submit_dance.py configs/motrv2.args exps/motrv2/run4
cp: cannot stat 'eval_detr.py': No such file or directory
cp: cannot stat 'seqmap': No such file or directory
+ echo ' ...Done'
 ...Done
++ cat configs/motrv2.args
+ args='--meta_arch motr
--dataset_file e2e_dance
--epoch 5
--with_box_refine
--lr_drop 4
--lr 2e-4
--lr_backbone 2e-5
--pretrained mot/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth
--batch_size 128
--sample_mode random_interval
--sample_interval 10
--sampler_lengths 5
--merger_dropout 0
--dropout 0
--random_drop 0.1
--fp_ratio 0.3
--query_interaction_layer QIMv2
--query_denoise 0.05
--num_queries 10
--append_crowd
--det_db det_db_motrv2.json
'-use_checkpoint
+ pushd exps/motrv2/run4
~/MOTRv2/exps/motrv2/run4 ~/MOTRv2
+ trap cleanup EXIT
+ echo 'Logging git status'
Logging git status
+ git status
+ git rev-parse HEAD
+ git diff
+ echo
+ echo ' ...Done'
 ...Done
+ tee -a output.log
+ python -m torch.distributed.run --nproc_per_node=6 --use_env main.py --meta_arch $'motr\r' --dataset_file $'e2e_dance\r' --epoch $'5\r' $'--with_box_refine\r' --lr_drop $'4\r' --lr $'2e-4\r' --lr_backbone $'2e-5\r' --pretrained $'mot/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth\r' --batch_size $'128\r' --sample_mode $'random_interval\r' --sample_interval $'10\r' --sampler_lengths $'5\r' --merger_dropout $'0\r' --dropout $'0\r' --random_drop $'0.1\r' --fp_ratio $'0.3\r' --query_interaction_layer $'QIMv2\r' --query_denoise $'0.05\r' --num_queries $'10\r' $'--append_crowd\r' --det_db $'det_db_motrv2.json\r' $'--use_checkpoint\r' --output_dir .
/data1/dcy/anaconda3/envs/motrv2/bin/python: No module named torch.distributed.run
+ cleanup
+ echo 'Packing source code'
Packing source code
+ rmpyc
++ find -name __pycache__
+ rm -rf
++ find -name '*.pyc'
+ rm -rf
+ echo ' ...Done'
 ...Done
(motrv2) dcy@ubuntu:~/MOTRv2$ bash tools/train.sh configs/motrv2.args
+ PY_ARGS=
+ set -o pipefail
++ echo configs/motrv2.args
++ sed -e s/configs/exps/g
++ sed -e 's/.args$//g'
+ OUTPUT_BASE=exps/motrv2
+ mkdir -p exps/motrv2
++ seq 100
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run1
run1
+ continue
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run2
run2
+ continue
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run3
run3
+ continue
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run4
run4
+ continue
+ for RUN in $(seq 100)
+ ls exps/motrv2
+ grep run5
+ OUTPUT_DIR=exps/motrv2/run5
+ mkdir exps/motrv2/run5
+ break
+ echo 'Backing up to log dir: exps/motrv2/run5'
Backing up to log dir: exps/motrv2/run5
+ rmpyc
++ find -name __pycache__
+ rm -rf
++ find -name '*.pyc'
+ rm -rf
+ cp -r models datasets util main.py engine.py eval_detr.py seqmap submit_dance.py configs/motrv2.args exps/motrv2/run5
cp: cannot stat 'eval_detr.py': No such file or directory
cp: cannot stat 'seqmap': No such file or directory
+ echo ' ...Done'
 ...Done
++ cat configs/motrv2.args
+ args='--meta_arch motr
--dataset_file e2e_dance
--epoch 5
--with_box_refine
--lr_drop 4
--lr 2e-4
--lr_backbone 2e-5
--pretrained mot/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth
--batch_size 128
--sample_mode random_interval
--sample_interval 10
--sampler_lengths 5
--merger_dropout 0
--dropout 0
--random_drop 0.1
--fp_ratio 0.3
--query_interaction_layer QIMv2
--query_denoise 0.05
--num_queries 10
--append_crowd
--det_db det_db_motrv2.json
'-use_checkpoint
+ pushd exps/motrv2/run5
~/MOTRv2/exps/motrv2/run5 ~/MOTRv2
+ trap cleanup EXIT
+ echo 'Logging git status'
Logging git status
+ git status
+ git rev-parse HEAD
+ git diff
+ echo
+ echo ' ...Done'
 ...Done
+ python -m torch.distributed.launch --nproc_per_node=6 --use_env main.py --meta_arch $'motr\r' --dataset_file $'e2e_dance\r' --epoch $'5\r' $'--with_box_refine\r' --lr_drop $'4\r' --lr $'2e-4\r' --lr_backbone $'2e-5\r' --pretrained $'mot/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth\r' --batch_size $'128\r' --sample_mode $'random_interval\r' --sample_interval $'10\r' --sampler_lengths $'5\r' --merger_dropout $'0\r' --dropout $'0\r' --random_drop $'0.1\r' --fp_ratio $'0.3\r' --query_interaction_layer $'QIMv2\r' --query_denoise $'0.05\r' --num_queries $'10\r' $'--append_crowd\r' --det_db $'det_db_motrv2.json\r' $'--use_checkpoint\r' --output_dir .
+ tee -a output.log
usage: Deformable DETR training and evaluation script [-h] [--lr LR]
                                                      [--lr_backbone_names LR_BACKBONE_NAMES [LR_BACKBONE_NAMES ...]]
                                                      [--lr_backbone LR_BACKBONE]
                                                      [--lr_linear_proj_names LR_LINEAR_PROJ_NAMES [LR_LINEAR_PROJ_NAMES ...]]
                                                      [--lr_linear_proj_mult LR_LINEAR_PROJ_MULT]
                                                      [--batch_size BATCH_SIZE]
                                                      [--weight_decay WEIGHT_DECAY]
                                                      [--epochs EPOCHS]
                                                      [--lr_drop LR_DROP]
                                                      [--save_period SAVE_PERIOD]
                                                      [--lr_drop_epochs LR_DROP_EPOCHS [LR_DROP_EPOCHS ...]]
                                                      [--clip_max_norm CLIP_MAX_NORM]
                                                      [--meta_arch META_ARCH]
                                                      [--sgd]
                                                      [--with_box_refine]
                                                      [--two_stage]
                                                      [--accurate_ratio]
                                                      [--frozen_weights FROZEN_WEIGHTS]
                                                      [--num_anchors NUM_ANCHORS]
                                                      [--backbone BACKBONE]
                                                      [--enable_fpn]
                                                      [--dilation]
                                                      [--position_embedding {sine,learned}]
                                                      [--position_embedding_scale POSITION_EMBEDDING_SCALE]
                                                      [--num_feature_levels NUM_FEATURE_LEVELS]
                                                      [--enc_layers ENC_LAYERS]
                                                      [--dec_layers DEC_LAYERS]
                                                      [--dim_feedforward DIM_FEEDFORWARD]
                                                      [--hidden_dim HIDDEN_DIM]
                                                      [--dropout DROPOUT]
                                                      [--nheads NHEADS]
                                                      [--num_queries NUM_QUERIES]
                                                      [--dec_n_points DEC_N_POINTS]
                                                      [--enc_n_points ENC_N_POINTS]
                                                      [--decoder_cross_self]
                                                      [--sigmoid_attn]
                                                      [--crop] [--cj]
                                                      [--extra_track_attn]
                                                      [--loss_normalizer]
                                                      [--max_size MAX_SIZE]
                                                      [--val_width VAL_WIDTH]
                                                      [--filter_ignore]
                                                      [--append_crowd]
                                                      [--masks]
                                                      [--no_aux_loss]
                                                      [--mix_match]
                                                      [--set_cost_class SET_COST_CLASS]
                                                      [--set_cost_bbox SET_COST_BBOX]
                                                      [--set_cost_giou SET_COST_GIOU]
                                                      [--mask_loss_coef MASK_LOSS_COEF]
                                                      [--dice_loss_coef DICE_LOSS_COEF]
                                                      [--cls_loss_coef CLS_LOSS_COEF]
                                                      [--bbox_loss_coef BBOX_LOSS_COEF]
                                                      [--giou_loss_coef GIOU_LOSS_COEF]
                                                      [--focal_alpha FOCAL_ALPHA]
                                                      [--dataset_file DATASET_FILE]
                                                      [--gt_file_train GT_FILE_TRAIN]
                                                      [--gt_file_val GT_FILE_VAL]
                                                      [--coco_path COCO_PATH]
                                                      [--coco_panoptic_path COCO_PANOPTIC_PATH]
                                                      [--remove_difficult]
                                                      [--output_dir OUTPUT_DIR]
                                                      [--device DEVICE]
                                                      [--seed SEED]
                                                      [--resume RESUME]
                                                      [--start_epoch N]
                                                      [--eval] [--vis]
                                                      [--num_workers NUM_WORKERS]
                                                      [--pretrained PRETRAINED]
                                                      [--cache_mode]
                                                      [--mot_path MOT_PATH]
                                                      [--det_db DET_DB]
                                                      [--input_video INPUT_VIDEO]
                                                      [--data_txt_path_train DATA_TXT_PATH_TRAIN]
                                                      [--data_txt_path_val DATA_TXT_PATH_VAL]
                                                      [--img_path IMG_PATH]
                                                      [--query_interaction_layer QUERY_INTERACTION_LAYER]
                                                      [--sample_mode SAMPLE_MODE]
                                                      [--sample_interval SAMPLE_INTERVAL]
                                                      [--random_drop RANDOM_DROP]
                                                      [--fp_ratio FP_RATIO]
                                                      [--merger_dropout MERGER_DROPOUT]
                                                      [--update_query_pos]
                                                      [--sampler_steps [SAMPLER_STEPS [SAMPLER_STEPS ...]]]
                                                      [--sampler_lengths [SAMPLER_LENGTHS [SAMPLER_LENGTHS ...]]]
                                                      [--exp_name EXP_NAME]
                                                      [--memory_bank_score_thresh MEMORY_BANK_SCORE_THRESH]
                                                      [--memory_bank_len MEMORY_BANK_LEN]
                                                      [--memory_bank_type MEMORY_BANK_TYPE]
                                                      [--memory_bank_with_self_attn]
                                                      [--use_checkpoint]
                                                      [--query_denoise QUERY_DENOISE]
 --use_checkpointraining and evaluation script: error: unrecognized arguments: --with_box_refine
usage: Deformable DETR training and evaluation script [-h] [--lr LR]
                                                      [--lr_backbone_names LR_BACKBONE_NAMES [LR_BACKBONE_NAMES ...]]
                                                      [--lr_backbone LR_BACKBONE]
                                                      [--lr_linear_proj_names LR_LINEAR_PROJ_NAMES [LR_LINEAR_PROJ_NAMES ...]]
                                                      [--lr_linear_proj_mult LR_LINEAR_PROJ_MULT]
                                                      [--batch_size BATCH_SIZE]
                                                      [--weight_decay WEIGHT_DECAY]
                                                      [--epochs EPOCHS]
                                                      [--lr_drop LR_DROP]
                                                      [--save_period SAVE_PERIOD]
                                                      [--lr_drop_epochs LR_DROP_EPOCHS [LR_DROP_EPOCHS ...]]
                                                      [--clip_max_norm CLIP_MAX_NORM]
                                                      [--meta_arch META_ARCH]
                                                      [--sgd]
                                                      [--with_box_refine]
                                                      [--two_stage]
                                                      [--accurate_ratio]
                                                      [--frozen_weights FROZEN_WEIGHTS]
                                                      [--num_anchors NUM_ANCHORS]
                                                      [--backbone BACKBONE]
                                                      [--enable_fpn]
                                                      [--dilation]
                                                      [--position_embedding {sine,learned}]
                                                      [--position_embedding_scale POSITION_EMBEDDING_SCALE]
                                                      [--num_feature_levels NUM_FEATURE_LEVELS]
                                                      [--enc_layers ENC_LAYERS]
                                                      [--dec_layers DEC_LAYERS]
                                                      [--dim_feedforward DIM_FEEDFORWARD]
                                                      [--hidden_dim HIDDEN_DIM]
                                                      [--dropout DROPOUT]
                                                      [--nheads NHEADS]
                                                      [--num_queries NUM_QUERIES]
                                                      [--dec_n_points DEC_N_POINTS]
                                                      [--enc_n_points ENC_N_POINTS]
                                                      [--decoder_cross_self]
                                                      [--sigmoid_attn]
                                                      [--crop] [--cj]
                                                      [--extra_track_attn]
                                                      [--loss_normalizer]
                                                      [--max_size MAX_SIZE]
                                                      [--val_width VAL_WIDTH]
                                                      [--filter_ignore]
                                                      [--append_crowd]
                                                      [--masks]
                                                      [--no_aux_loss]
                                                      [--mix_match]
                                                      [--set_cost_class SET_COST_CLASS]
                                                      [--set_cost_bbox SET_COST_BBOX]
                                                      [--set_cost_giou SET_COST_GIOU]
                                                      [--mask_loss_coef MASK_LOSS_COEF]
                                                      [--dice_loss_coef DICE_LOSS_COEF]
                                                      [--cls_loss_coef CLS_LOSS_COEF]
                                                      [--bbox_loss_coef BBOX_LOSS_COEF]
                                                      [--giou_loss_coef GIOU_LOSS_COEF]
                                                      [--focal_alpha FOCAL_ALPHA]
                                                      [--dataset_file DATASET_FILE]
                                                      [--gt_file_train GT_FILE_TRAIN]
                                                      [--gt_file_val GT_FILE_VAL]
                                                      [--coco_path COCO_PATH]
                                                      [--coco_panoptic_path COCO_PANOPTIC_PATH]
                                                      [--remove_difficult]
                                                      [--output_dir OUTPUT_DIR]
                                                      [--device DEVICE]
                                                      [--seed SEED]
                                                      [--resume RESUME]
                                                      [--start_epoch N]
                                                      [--eval] [--vis]
                                                      [--num_workers NUM_WORKERS]
                                                      [--pretrained PRETRAINED]
                                                      [--cache_mode]
                                                      [--mot_path MOT_PATH]
                                                      [--det_db DET_DB]
                                                      [--input_video INPUT_VIDEO]
                                                      [--data_txt_path_train DATA_TXT_PATH_TRAIN]
                                                      [--data_txt_path_val DATA_TXT_PATH_VAL]
                                                      [--img_path IMG_PATH]
                                                      [--query_interaction_layer QUERY_INTERACTION_LAYER]
                                                      [--sample_mode SAMPLE_MODE]
                                                      [--sample_interval SAMPLE_INTERVAL]
                                                      [--random_drop RANDOM_DROP]
                                                      [--fp_ratio FP_RATIO]
                                                      [--merger_dropout MERGER_DROPOUT]
                                                      [--update_query_pos]
                                                      [--sampler_steps [SAMPLER_STEPS [SAMPLER_STEPS ...]]]
                                                      [--sampler_lengths [SAMPLER_LENGTHS [SAMPLER_LENGTHS ...]]]
                                                      [--exp_name EXP_NAME]
                                                      [--memory_bank_score_thresh MEMORY_BANK_SCORE_THRESH]
                                                      [--memory_bank_len MEMORY_BANK_LEN]
                                                      [--memory_bank_type MEMORY_BANK_TYPE]
                                                      [--memory_bank_with_self_attn]
                                                      [--use_checkpoint]
                                                      [--query_denoise QUERY_DENOISE]
 --use_checkpointraining and evaluation script: error: unrecognized arguments: --with_box_refine
usage: Deformable DETR training and evaluation script [-h] [--lr LR]
                                                      [--lr_backbone_names LR_BACKBONE_NAMES [LR_BACKBONE_NAMES ...]]
                                                      [--lr_backbone LR_BACKBONE]
                                                      [--lr_linear_proj_names LR_LINEAR_PROJ_NAMES [LR_LINEAR_PROJ_NAMES ...]]
                                                      [--lr_linear_proj_mult LR_LINEAR_PROJ_MULT]
                                                      [--batch_size BATCH_SIZE]
                                                      [--weight_decay WEIGHT_DECAY]
                                                      [--epochs EPOCHS]
                                                      [--lr_drop LR_DROP]
                                                      [--save_period SAVE_PERIOD]
                                                      [--lr_drop_epochs LR_DROP_EPOCHS [LR_DROP_EPOCHS ...]]
                                                      [--clip_max_norm CLIP_MAX_NORM]
                                                      [--meta_arch META_ARCH]
                                                      [--sgd]
                                                      [--with_box_refine]
                                                      [--two_stage]
                                                      [--accurate_ratio]
                                                      [--frozen_weights FROZEN_WEIGHTS]
                                                      [--num_anchors NUM_ANCHORS]
                                                      [--backbone BACKBONE]
                                                      [--enable_fpn]
                                                      [--dilation]
                                                      [--position_embedding {sine,learned}]
                                                      [--position_embedding_scale POSITION_EMBEDDING_SCALE]
                                                      [--num_feature_levels NUM_FEATURE_LEVELS]
                                                      [--enc_layers ENC_LAYERS]
                                                      [--dec_layers DEC_LAYERS]
                                                      [--dim_feedforward DIM_FEEDFORWARD]
                                                      [--hidden_dim HIDDEN_DIM]
                                                      [--dropout DROPOUT]
                                                      [--nheads NHEADS]
                                                      [--num_queries NUM_QUERIES]
                                                      [--dec_n_points DEC_N_POINTS]
                                                      [--enc_n_points ENC_N_POINTS]
                                                      [--decoder_cross_self]
                                                      [--sigmoid_attn]
                                                      [--crop] [--cj]
                                                      [--extra_track_attn]
                                                      [--loss_normalizer]
                                                      [--max_size MAX_SIZE]
                                                      [--val_width VAL_WIDTH]
                                                      [--filter_ignore]
                                                      [--append_crowd]
                                                      [--masks]
                                                      [--no_aux_loss]
                                                      [--mix_match]
                                                      [--set_cost_class SET_COST_CLASS]
                                                      [--set_cost_bbox SET_COST_BBOX]
                                                      [--set_cost_giou SET_COST_GIOU]
                                                      [--mask_loss_coef MASK_LOSS_COEF]
                                                      [--dice_loss_coef DICE_LOSS_COEF]
                                                      [--cls_loss_coef CLS_LOSS_COEF]
                                                      [--bbox_loss_coef BBOX_LOSS_COEF]
                                                      [--giou_loss_coef GIOU_LOSS_COEF]
                                                      [--focal_alpha FOCAL_ALPHA]
                                                      [--dataset_file DATASET_FILE]
                                                      [--gt_file_train GT_FILE_TRAIN]
                                                      [--gt_file_val GT_FILE_VAL]
                                                      [--coco_path COCO_PATH]
                                                      [--coco_panoptic_path COCO_PANOPTIC_PATH]
                                                      [--remove_difficult]
                                                      [--output_dir OUTPUT_DIR]
                                                      [--device DEVICE]
                                                      [--seed SEED]
                                                      [--resume RESUME]
                                                      [--start_epoch N]
                                                      [--eval] [--vis]
                                                      [--num_workers NUM_WORKERS]
                                                      [--pretrained PRETRAINED]
                                                      [--cache_mode]
                                                      [--mot_path MOT_PATH]
                                                      [--det_db DET_DB]
                                                      [--input_video INPUT_VIDEO]
                                                      [--data_txt_path_train DATA_TXT_PATH_TRAIN]
                                                      [--data_txt_path_val DATA_TXT_PATH_VAL]
                                                      [--img_path IMG_PATH]
                                                      [--query_interaction_layer QUERY_INTERACTION_LAYER]
                                                      [--sample_mode SAMPLE_MODE]
                                                      [--sample_interval SAMPLE_INTERVAL]
                                                      [--random_drop RANDOM_DROP]
                                                      [--fp_ratio FP_RATIO]
                                                      [--merger_dropout MERGER_DROPOUT]
                                                      [--update_query_pos]
                                                      [--sampler_steps [SAMPLER_STEPS [SAMPLER_STEPS ...]]]
                                                      [--sampler_lengths [SAMPLER_LENGTHS [SAMPLER_LENGTHS ...]]]
                                                      [--exp_name EXP_NAME]
                                                      [--memory_bank_score_thresh MEMORY_BANK_SCORE_THRESH]
                                                      [--memory_bank_len MEMORY_BANK_LEN]
                                                      [--memory_bank_type MEMORY_BANK_TYPE]
                                                      [--memory_bank_with_self_attn]
                                                      [--use_checkpoint]
                                                      [--query_denoise QUERY_DENOISE]
 --use_checkpointraining and evaluation script: error: unrecognized arguments: --with_box_refine
usage: Deformable DETR training and evaluation script [-h] [--lr LR]
                                                      [--lr_backbone_names LR_BACKBONE_NAMES [LR_BACKBONE_NAMES ...]]
                                                      [--lr_backbone LR_BACKBONE]
                                                      [--lr_linear_proj_names LR_LINEAR_PROJ_NAMES [LR_LINEAR_PROJ_NAMES ...]]
                                                      [--lr_linear_proj_mult LR_LINEAR_PROJ_MULT]
                                                      [--batch_size BATCH_SIZE]
                                                      [--weight_decay WEIGHT_DECAY]
                                                      [--epochs EPOCHS]
                                                      [--lr_drop LR_DROP]
                                                      [--save_period SAVE_PERIOD]
                                                      [--lr_drop_epochs LR_DROP_EPOCHS [LR_DROP_EPOCHS ...]]
                                                      [--clip_max_norm CLIP_MAX_NORM]
                                                      [--meta_arch META_ARCH]
                                                      [--sgd]
                                                      [--with_box_refine]
                                                      [--two_stage]
                                                      [--accurate_ratio]
                                                      [--frozen_weights FROZEN_WEIGHTS]
                                                      [--num_anchors NUM_ANCHORS]
                                                      [--backbone BACKBONE]
                                                      [--enable_fpn]
                                                      [--dilation]
                                                      [--position_embedding {sine,learned}]
                                                      [--position_embedding_scale POSITION_EMBEDDING_SCALE]
                                                      [--num_feature_levels NUM_FEATURE_LEVELS]
                                                      [--enc_layers ENC_LAYERS]
                                                      [--dec_layers DEC_LAYERS]
                                                      [--dim_feedforward DIM_FEEDFORWARD]
                                                      [--hidden_dim HIDDEN_DIM]
                                                      [--dropout DROPOUT]
                                                      [--nheads NHEADS]
                                                      [--num_queries NUM_QUERIES]
                                                      [--dec_n_points DEC_N_POINTS]
                                                      [--enc_n_points ENC_N_POINTS]
                                                      [--decoder_cross_self]
                                                      [--sigmoid_attn]
                                                      [--crop] [--cj]
                                                      [--extra_track_attn]
                                                      [--loss_normalizer]
                                                      [--max_size MAX_SIZE]
                                                      [--val_width VAL_WIDTH]
                                                      [--filter_ignore]
                                                      [--append_crowd]
                                                      [--masks]
                                                      [--no_aux_loss]
                                                      [--mix_match]
                                                      [--set_cost_class SET_COST_CLASS]
                                                      [--set_cost_bbox SET_COST_BBOX]
                                                      [--set_cost_giou SET_COST_GIOU]
                                                      [--mask_loss_coef MASK_LOSS_COEF]
                                                      [--dice_loss_coef DICE_LOSS_COEF]
                                                      [--cls_loss_coef CLS_LOSS_COEF]
                                                      [--bbox_loss_coef BBOX_LOSS_COEF]
                                                      [--giou_loss_coef GIOU_LOSS_COEF]
                                                      [--focal_alpha FOCAL_ALPHA]
                                                      [--dataset_file DATASET_FILE]
                                                      [--gt_file_train GT_FILE_TRAIN]
                                                      [--gt_file_val GT_FILE_VAL]
                                                      [--coco_path COCO_PATH]
                                                      [--coco_panoptic_path COCO_PANOPTIC_PATH]
                                                      [--remove_difficult]
                                                      [--output_dir OUTPUT_DIR]
                                                      [--device DEVICE]
                                                      [--seed SEED]
                                                      [--resume RESUME]
                                                      [--start_epoch N]
                                                      [--eval] [--vis]
                                                      [--num_workers NUM_WORKERS]
                                                      [--pretrained PRETRAINED]
                                                      [--cache_mode]
                                                      [--mot_path MOT_PATH]
                                                      [--det_db DET_DB]
                                                      [--input_video INPUT_VIDEO]
                                                      [--data_txt_path_train DATA_TXT_PATH_TRAIN]
                                                      [--data_txt_path_val DATA_TXT_PATH_VAL]
                                                      [--img_path IMG_PATH]
                                                      [--query_interaction_layer QUERY_INTERACTION_LAYER]
                                                      [--sample_mode SAMPLE_MODE]
                                                      [--sample_interval SAMPLE_INTERVAL]
                                                      [--random_drop RANDOM_DROP]
                                                      [--fp_ratio FP_RATIO]
                                                      [--merger_dropout MERGER_DROPOUT]
                                                      [--update_query_pos]
                                                      [--sampler_steps [SAMPLER_STEPS [SAMPLER_STEPS ...]]]
                                                      [--sampler_lengths [SAMPLER_LENGTHS [SAMPLER_LENGTHS ...]]]
                                                      [--exp_name EXP_NAME]
                                                      [--memory_bank_score_thresh MEMORY_BANK_SCORE_THRESH]
                                                      [--memory_bank_len MEMORY_BANK_LEN]
                                                      [--memory_bank_type MEMORY_BANK_TYPE]
                                                      [--memory_bank_with_self_attn]
                                                      [--use_checkpoint]
                                                      [--query_denoise QUERY_DENOISE]
usage: Deformable DETR training and evaluation script [-h] [--lr LR]
                                                      [--lr_backbone_names LR_BACKBONE_NAMES [LR_BACKBONE_NAMES ...]]
                                                      [--lr_backbone LR_BACKBONE]
                                                      [--lr_linear_proj_names LR_LINEAR_PROJ_NAMES [LR_LINEAR_PROJ_NAMES ...]]
                                                      [--lr_linear_proj_mult LR_LINEAR_PROJ_MULT]
                                                      [--batch_size BATCH_SIZE]
                                                      [--weight_decay WEIGHT_DECAY]
                                                      [--epochs EPOCHS]
                                                      [--lr_drop LR_DROP]
                                                      [--save_period SAVE_PERIOD]
                                                      [--lr_drop_epochs LR_DROP_EPOCHS [LR_DROP_EPOCHS ...]]
                                                      [--clip_max_norm CLIP_MAX_NORM]
                                                      [--meta_arch META_ARCH]
                                                      [--sgd]
                                                      [--with_box_refine]
                                                      [--two_stage]
                                                      [--accurate_ratio]
                                                      [--frozen_weights FROZEN_WEIGHTS]
                                                      [--num_anchors NUM_ANCHORS]
                                                      [--backbone BACKBONE]
                                                      [--enable_fpn]
                                                      [--dilation]
                                                      [--position_embedding {sine,learned}]
                                                      [--position_embedding_scale POSITION_EMBEDDING_SCALE]
                                                      [--num_feature_levels NUM_FEATURE_LEVELS]
                                                      [--enc_layers ENC_LAYERS]
                                                      [--dec_layers DEC_LAYERS]
                                                      [--dim_feedforward DIM_FEEDFORWARD]
                                                      [--hidden_dim HIDDEN_DIM]
                                                      [--dropout DROPOUT]
                                                      [--nheads NHEADS]
                                                      [--num_queries NUM_QUERIES]
                                                      [--dec_n_points DEC_N_POINTS]
                                                      [--enc_n_points ENC_N_POINTS]
                                                      [--decoder_cross_self]
                                                      [--sigmoid_attn]
                                                      [--crop] [--cj]
                                                      [--extra_track_attn]
                                                      [--loss_normalizer]
                                                      [--max_size MAX_SIZE]
                                                      [--val_width VAL_WIDTH]
                                                      [--filter_ignore]
                                                      [--append_crowd]
                                                      [--masks]
                                                      [--no_aux_loss]
                                                      [--mix_match]
                                                      [--set_cost_class SET_COST_CLASS]
                                                      [--set_cost_bbox SET_COST_BBOX]
                                                      [--set_cost_giou SET_COST_GIOU]
                                                      [--mask_loss_coef MASK_LOSS_COEF]
                                                      [--dice_loss_coef DICE_LOSS_COEF]
                                                      [--cls_loss_coef CLS_LOSS_COEF]
                                                      [--bbox_loss_coef BBOX_LOSS_COEF]
                                                      [--giou_loss_coef GIOU_LOSS_COEF]
                                                      [--focal_alpha FOCAL_ALPHA]
                                                      [--dataset_file DATASET_FILE]
                                                      [--gt_file_train GT_FILE_TRAIN]
                                                      [--gt_file_val GT_FILE_VAL]
                                                      [--coco_path COCO_PATH]
                                                      [--coco_panoptic_path COCO_PANOPTIC_PATH]
                                                      [--remove_difficult]
                                                      [--output_dir OUTPUT_DIR]
                                                      [--device DEVICE]
                                                      [--seed SEED]
                                                      [--resume RESUME]
                                                      [--start_epoch N]
                                                      [--eval] [--vis]
                                                      [--num_workers NUM_WORKERS]
                                                      [--pretrained PRETRAINED]
                                                      [--cache_mode]
                                                      [--mot_path MOT_PATH]
                                                      [--det_db DET_DB]
                                                      [--input_video INPUT_VIDEO]
                                                      [--data_txt_path_train DATA_TXT_PATH_TRAIN]
                                                      [--data_txt_path_val DATA_TXT_PATH_VAL]
                                                      [--img_path IMG_PATH]
                                                      [--query_interaction_layer QUERY_INTERACTION_LAYER]
                                                      [--sample_mode SAMPLE_MODE]
                                                      [--sample_interval SAMPLE_INTERVAL]
                                                      [--random_drop RANDOM_DROP]
                                                      [--fp_ratio FP_RATIO]
                                                      [--merger_dropout MERGER_DROPOUT]
                                                      [--update_query_pos]
                                                      [--sampler_steps [SAMPLER_STEPS [SAMPLER_STEPS ...]]]
                                                      [--sampler_lengths [SAMPLER_LENGTHS [SAMPLER_LENGTHS ...]]]
                                                      [--exp_name EXP_NAME]
                                                      [--memory_bank_score_thresh MEMORY_BANK_SCORE_THRESH]
                                                      [--memory_bank_len MEMORY_BANK_LEN]
                                                      [--memory_bank_type MEMORY_BANK_TYPE]
                                                      [--memory_bank_with_self_attn]
                                                      [--use_checkpoint]
                                                      [--query_denoise QUERY_DENOISE]
usage: Deformable DETR training and evaluation script [-h] [--lr LR]
                                                      [--lr_backbone_names LR_BACKBONE_NAMES [LR_BACKBONE_NAMES ...]]
                                                      [--lr_backbone LR_BACKBONE]
                                                      [--lr_linear_proj_names LR_LINEAR_PROJ_NAMES [LR_LINEAR_PROJ_NAMES ...]]
                                                      [--lr_linear_proj_mult LR_LINEAR_PROJ_MULT]
                                                      [--batch_size BATCH_SIZE]
                                                      [--weight_decay WEIGHT_DECAY]
                                                      [--epochs EPOCHS]
                                                      [--lr_drop LR_DROP]
                                                      [--save_period SAVE_PERIOD]
                                                      [--lr_drop_epochs LR_DROP_EPOCHS [LR_DROP_EPOCHS ...]]
                                                      [--clip_max_norm CLIP_MAX_NORM]
                                                      [--meta_arch META_ARCH]
                                                      [--sgd]
                                                      [--with_box_refine]
                                                      [--two_stage]
                                                      [--accurate_ratio]
                                                      [--frozen_weights FROZEN_WEIGHTS]
                                                      [--num_anchors NUM_ANCHORS]
                                                      [--backbone BACKBONE]
                                                      [--enable_fpn]
                                                      [--dilation]
                                                      [--position_embedding {sine,learned}]
                                                      [--position_embedding_scale POSITION_EMBEDDING_SCALE]
                                                      [--num_feature_levels NUM_FEATURE_LEVELS]
                                                      [--enc_layers ENC_LAYERS]
                                                      [--dec_layers DEC_LAYERS]
                                                      [--dim_feedforward DIM_FEEDFORWARD]
                                                      [--hidden_dim HIDDEN_DIM]
                                                      [--dropout DROPOUT]
                                                      [--nheads NHEADS]
                                                      [--num_queries NUM_QUERIES]
                                                      [--dec_n_points DEC_N_POINTS]
                                                      [--enc_n_points ENC_N_POINTS]
                                                      [--decoder_cross_self]
                                                      [--sigmoid_attn]
                                                      [--crop] [--cj]
                                                      [--extra_track_attn]
                                                      [--loss_normalizer]
                                                      [--max_size MAX_SIZE]
                                                      [--val_width VAL_WIDTH]
                                                      [--filter_ignore]
                                                      [--append_crowd]
                                                      [--masks]
                                                      [--no_aux_loss]
                                                      [--mix_match]
                                                      [--set_cost_class SET_COST_CLASS]
                                                      [--set_cost_bbox SET_COST_BBOX]
                                                      [--set_cost_giou SET_COST_GIOU]
                                                      [--mask_loss_coef MASK_LOSS_COEF]
                                                      [--dice_loss_coef DICE_LOSS_COEF]
                                                      [--cls_loss_coef CLS_LOSS_COEF]
                                                      [--bbox_loss_coef BBOX_LOSS_COEF]
                                                      [--giou_loss_coef GIOU_LOSS_COEF]
                                                      [--focal_alpha FOCAL_ALPHA]
                                                      [--dataset_file DATASET_FILE]
                                                      [--gt_file_train GT_FILE_TRAIN]
                                                      [--gt_file_val GT_FILE_VAL]
                                                      [--coco_path COCO_PATH]
                                                      [--coco_panoptic_path COCO_PANOPTIC_PATH]
                                                      [--remove_difficult]
                                                      [--output_dir OUTPUT_DIR]
                                                      [--device DEVICE]
                                                      [--seed SEED]
                                                      [--resume RESUME]
                                                      [--start_epoch N]
                                                      [--eval] [--vis]
                                                      [--num_workers NUM_WORKERS]
                                                      [--pretrained PRETRAINED]
                                                      [--cache_mode]
                                                      [--mot_path MOT_PATH]
                                                      [--det_db DET_DB]
                                                      [--input_video INPUT_VIDEO]
                                                      [--data_txt_path_train DATA_TXT_PATH_TRAIN]
                                                      [--data_txt_path_val DATA_TXT_PATH_VAL]
                                                      [--img_path IMG_PATH]
                                                      [--query_interaction_layer QUERY_INTERACTION_LAYER]
                                                      [--sample_mode SAMPLE_MODE]
                                                      [--sample_interval SAMPLE_INTERVAL]
                                                      [--random_drop RANDOM_DROP]
                                                      [--fp_ratio FP_RATIO]
                                                      [--merger_dropout MERGER_DROPOUT]
                                                      [--update_query_pos]
                                                      [--sampler_steps [SAMPLER_STEPS [SAMPLER_STEPS ...]]]
                                                      [--sampler_lengths [SAMPLER_LENGTHS [SAMPLER_LENGTHS ...]]]
                                                      [--exp_name EXP_NAME]
                                                      [--memory_bank_score_thresh MEMORY_BANK_SCORE_THRESH]
                                                      [--memory_bank_len MEMORY_BANK_LEN]
                                                      [--memory_bank_type MEMORY_BANK_TYPE]
                                                      [--memory_bank_with_self_attn]
                                                      [--use_checkpoint]
                                                      [--query_denoise QUERY_DENOISE]
 --use_checkpointraining and evaluation script: error: unrecognized arguments: --with_box_refine
 --use_checkpointraining and evaluation script: error: unrecognized arguments: --with_box_refine
 --use_checkpointraining and evaluation script: error: unrecognized arguments: --with_box_refine
Traceback (most recent call last):
  File "/data1/dcy/anaconda3/envs/motrv2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data1/dcy/anaconda3/envs/motrv2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/dcy/anaconda3/envs/motrv2/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/data1/dcy/anaconda3/envs/motrv2/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/data1/dcy/anaconda3/envs/motrv2/bin/python', '-u', 'main.py', '--meta_arch', 'motr\r', '--dataset_file', 'e2e_dance\r', '--epoch', '5\r', '--with_box_refine\r', '--lr_drop', '4\r', '--lr', '2e-4\r', '--lr_backbone', '2e-5\r', '--pretrained', 'mot/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth\r', '--batch_size', '128\r', '--sample_mode', 'random_interval\r', '--sample_interval', '10\r', '--sampler_lengths', '5\r', '--merger_dropout', '0\r', '--dropout', '0\r', '--random_drop', '0.1\r', '--fp_ratio', '0.3\r', '--query_interaction_layer', 'QIMv2\r', '--query_denoise', '0.05\r', '--num_queries', '10\r', '--append_crowd\r', '--det_db', 'det_db_motrv2.json\r', '--use_checkpoint\r', '--output_dir', '.']' died with <Signals.SIGSEGV: 11>.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
+ cleanup
+ echo 'Packing source code'
Packing source code
+ rmpyc
++ find -name __pycache__
+ rm -rf ./__pycache__ ./datasets/__pycache__ ./models/__pycache__ ./models/ops/functions/__pycache__ ./models/ops/modules/__pycache__ ./models/structures/__pycache__ ./util/__pycache__
++ find -name '*.pyc'
+ rm -rf
+ echo ' ...Done'
 ...Done

**Comment by wh1sperC** [comment]
My environment is ubuntu-18.04,torch=1.7.1,python=3.7

**Comment by zyayoung** [comment]
The error is 
```
cp: cannot stat 'eval_detr.py': No such file or directory
cp: cannot stat 'seqmap': No such file or directory
```

Fixed in [a803eee](https://github.com/megvii-research/MOTRv2/commit/a803eeefa2812de0e8d18bb9ab2a591755cc16d4).

**Comment by wh1sperC** [comment]
OK,it's the encoding problem.I used to code in CRLF, but now I change it to LF.But there is still a problem that says 'Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.'How I can fix this problem?

**Comment by wh1sperC** [comment]
Oh my god,I found that error you say,sorry,it's my fault.But I don't know what should I do next,please help me how to avoid that problem you say?
